default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: waldo_development
  username: waldo
  password: <%= ENV['DB_PASS'] %>
test:
  <<: *default
  database: waldo_test
  username: waldo
  password: <%= ENV['DB_PASS'] %>
production:
  <<: *default
  database: waldo_production
  username: waldo
  password: <%= ENV['WALDO_DATABASE_PASSWORD'] %>
